server:
  port: 8787
spring:
  datasource:
    url: jdbc:mysql://39.103.33.73:3306/springcloud_provider?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&nullCatalogMeansCurrent=true&useSSL=false
    username: springcloud
    password: springcloud@123
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: provider
eureka:
  client:
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
logging:
  level:
    com.javaboy.provider.dao: debug


feign:
  hystrix:
    enabled: false

ribbon:
  ConnectTimeout: 50000
  ReadTimeout: 50000


